modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="osalysmod"
version="1.0.0"
displayName="OsalysMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://exolia.site"
authors="PLR, SkyScube, Ketchua_"
description='''
Mod Officiel d'Osalys
'''

[[dependencies.osalysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




